// Product data with real jacket/hoodie images from Unsplash
export const PRODUCTS = [
  // JACKETS
  // JACKETS
  {
    id: 'varsity-classic-black',
    name: 'Black Wool & Genuine Leather Varsity Letterman Jacket',
    shortName: 'Varsity Classic',
    category: 'jacket',
    gender: 'men',
    basePrice: 229,
    originalPrice: 299,
    description: 'A timeless varsity letterman crafted from premium black wool body with genuine full-grain leather sleeves. Features ribbed knit cuffs, collar, and hem, plus a snap-button front closure.',
    photos: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
      'https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    colors: [
      { name: 'Black / Black', body: '#111111', sleeve: '#0a0a0a', hex: '#111111' },
      { name: 'Navy / White',  body: '#1a2744', sleeve: '#FFFFFF', hex: '#1a2744' },
      { name: 'Forest / Tan',  body: '#2d4a2d', sleeve: '#c8a97e', hex: '#2d4a2d' },
      { name: 'Burgundy / Cream', body: '#6b1a2a', sleeve: '#f5e6d3', hex: '#6b1a2a' },
      { name: 'Camel / Brown', body: '#c8a05a', sleeve: '#8b5e3c', hex: '#c8a05a' },
    ],
    materials: { body: 'wool-melton', sleeve: 'genuine-leather' },
    specs: { closure: 'Snap Button', materials: 'Wool Body, Genuine Leather Sleeves', weight: '850g', origin: 'Made in USA' },
    tags: ['bestseller', 'classic'],
  },
  {
    id: 'bomber-navy',
    name: 'Navy Nylon Bomber Jacket',
    shortName: 'Bomber Pro',
    category: 'jacket',
    gender: 'men',
    basePrice: 199,
    originalPrice: 259,
    description: 'A sleek modern bomber in water-resistant nylon with contrast ribbing and a hidden zip. Lightweight, packable, and infinitely customizable.',
    photos: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
      'https://images.unsplash.com/photo-1559551409-dadc959f76b8?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
    colors: [
      { name: 'Navy / Navy',    body: '#1a2744', sleeve: '#1a2744', hex: '#1a2744' },
      { name: 'Olive / Black',  body: '#4a4a2a', sleeve: '#111111', hex: '#4a4a2a' },
    ],
    materials: { body: 'nylon', sleeve: 'nylon' },
    specs: { closure: 'YKK Zipper', materials: 'Nylon Shell, Mesh Lining', weight: '480g', origin: 'Made in Portugal' },
    tags: ['lightweight', 'new'],
  },
  {
    id: 'women-varsity-cropped',
    name: 'Cropped Wool Varsity Jacket',
    shortName: 'Cropped Varsity',
    category: 'jacket',
    gender: 'women',
    basePrice: 189,
    originalPrice: 249,
    description: 'A modern, cropped take on the classic varsity jacket. Premium wool body with soft leather sleeves and a tapered fit for a sleek silhouette.',
    photos: [
      'https://images.unsplash.com/photo-1618333234976-13a82dfbcff9?w=800&q=80',
      'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1618333234976-13a82dfbcff9?w=600&q=80',
    colors: [
      { name: 'Cream / White', body: '#F5E6D3', sleeve: '#FFFFFF', hex: '#F5E6D3' },
      { name: 'Pastel Blue',    body: '#A2C2E1', sleeve: '#FFFFFF', hex: '#A2C2E1' },
    ],
    materials: { body: 'wool-melton', sleeve: 'soft-leather' },
    specs: { closure: 'Snap Button', materials: 'Wool Body, Vegan Leather Sleeves', weight: '600g', origin: 'Made in Italy' },
    tags: ['women', 'new'],
  },
  {
    id: 'women-hoodie-slim',
    name: 'Slim-Fit Pastel Fleece Hoodie',
    shortName: 'Slim Hoodie',
    category: 'hoodie',
    gender: 'women',
    basePrice: 99,
    originalPrice: 139,
    description: 'A tailored, slim-fit hoodie in high-stretch cotton fleece. Perfect for layering or active wear with custom embroidery options.',
    photos: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80',
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',
    colors: [
      { name: 'Lavender', body: '#E6E6FA', sleeve: '#E6E6FA', hex: '#E6E6FA' },
      { name: 'Peach',    body: '#FFDAB9', sleeve: '#FFDAB9', hex: '#FFDAB9' },
    ],
    materials: { body: 'fleece', sleeve: 'fleece' },
    specs: { closure: 'Pullover', materials: 'Luxury Cotton Blend', weight: '400g', origin: 'Made in UK' },
    tags: ['essential', 'women'],
  },
  {
    id: 'oversized-hoodie',
    name: 'Oversized Drop-Shoulder Sherpa Hoodie',
    shortName: 'Sherpa Oversized',
    category: 'hoodie',
    gender: 'women',
    basePrice: 129,
    originalPrice: 179,
    description: 'Ultra-cozy sherpa-lined hoodie with a boxy drop shoulder silhouette. Features split kangaroo pocket and an oversized hood for dramatic presence.',
    photos: [
      'https://images.unsplash.com/photo-1608234807905-4466023792f5?w=800&q=80',
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1608234807905-4466023792f5?w=600&q=80',
    colors: [
      { name: 'Cream',       body: '#f5e6d3', sleeve: '#f5e6d3', hex: '#f5e6d3' },
      { name: 'Mocha Brown', body: '#6b4e37', sleeve: '#6b4e37', hex: '#6b4e37' },
    ],
    materials: { body: 'sherpa', sleeve: 'sherpa' },
    specs: { closure: 'Pullover', materials: 'Sherpa Fleece, Cotton Jersey', weight: '680g', origin: 'Made in Turkey' },
    tags: ['cozy', 'women'],
  },
  {
    id: 'kids-varsity-jr',
    name: "Junior's Varsity Jacket",
    shortName: 'Varsity Jr',
    category: 'jacket',
    gender: 'kids',
    basePrice: 129,
    originalPrice: 159,
    description: 'A durable, high-quality varsity jacket for the next generation. Features easy-to-clean materials and a comfortable fit for active kids.',
    photos: [
      'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80',
      'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&q=80',
    colors: [
      { name: 'Blue / Yellow', body: '#1E3A8A', sleeve: '#FBBF24', hex: '#1E3A8A' },
      { name: 'Red / Grey',   body: '#991B1B', sleeve: '#6B7280', hex: '#991B1B' },
    ],
    materials: { body: 'wool-blend', sleeve: 'synthetic-leather' },
    specs: { closure: 'Snap Button', materials: 'Polyester Blend', weight: '400g', origin: 'Made in Canada' },
    tags: ['kids', 'durable'],
  },
  {
    id: 'kids-hoodie-comfy',
    name: 'Signature Comfy Kids Hoodie',
    shortName: 'Comfy Jr',
    category: 'hoodie',
    gender: 'kids',
    basePrice: 69,
    originalPrice: 89,
    description: 'The ultimate everyday hoodie for kids. Soft, warm, and available in a variety of vibrant mix-and-match colors.',
    photos: [
      'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=800&q=80',
      'https://images.unsplash.com/photo-1519457431-75711ddc581b?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=600&q=80',
    colors: [
      { name: 'Bright Orange', body: '#FB923C', sleeve: '#FB923C', hex: '#FB923C' },
      { name: 'Sky Blue',      body: '#60A5FA', sleeve: '#60A5FA', hex: '#60A5FA' },
    ],
    materials: { body: 'fleece', sleeve: 'fleece' },
    specs: { closure: 'Pullover', materials: '100% Cotton Fleece', weight: '300g', origin: 'Made in USA' },
    tags: ['kids', 'bestseller'],
  },
  {
    id: 'varsity-red-white',
    name: 'Red & White Varsity Letterman Jacket',
    shortName: 'Varsity Red',
    category: 'jacket',
    gender: 'men',
    basePrice: 219,
    originalPrice: 279,
    description: 'Bold red wool body with crisp white genuine leather sleeves. The ultimate sports-inspired statement piece with precision stitching throughout.',
    photos: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80',
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=90',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
    colors: [
      { name: 'Red / White',  body: '#A80000', sleeve: '#FFFFFF', hex: '#A80000' },
    ],
    materials: { body: 'wool-melton', sleeve: 'genuine-leather' },
    specs: { closure: 'Snap Button', materials: 'Wool Body, Genuine Leather Sleeves', weight: '820g', origin: 'Made in USA' },
    tags: ['new', 'men'],
  },
];

export const SIZES = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'];

export const getProductById = (id) => PRODUCTS.find(p => p.id === id);
